---
# TODO for 'setup ansible' shell script:
# - Install aptitude and python-apt or python3-apt for the `apt` module

- hosts: localhost
  connection: local

  vars:
    # TODO: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    # TODO: Install the following via `flatpak install flathub [...]`:
    # - cc.arduino.arduinoide (TODO: See if this works if I narrow filesystem=home)
    # - io.github.antimicrox.antimicrox
    # - org.chromium.Chromium (with flatseal tweaks, better this than snap)
    #     or
    #   com.github.Eloston.UngoogledChromium (with flatseal tweaks)
    # - org.gottcode.FocusWriter (TODO: Decide if I want to lock down the filesystem access)
    # - org.inkscape.Inkscape  (TODO: See if this works w/o filesystem=host)
    # - org.jdownloader.JDownloader
    # - org.phoenicis.playonlinux
    # - com.github.tchx84.Flatseal (and incorporate changes into this script)
    # - org.zealdocs.Zeal
    #
    apt_install:
      # --== Dependencies for other parts of this playbook ==--
      - aptitude
      - apt-file
      - build-essential
      - curl
      - flatpak
      - git # shell alias
      - git-gui # file manager action
      - nodejs
      - pipx # TODO: Actually install things through pipx
      - libssl-dev # Needed for the user playbook
      - python-apt
      - python3-apt
      # --== Regular packages ==--
      - audacious
      - basket
      - comix
      # TODO: Verify that https://moritzmolch.com/apps/mencfsm.html can import
      # my Project4 cryptkeeper EncFS filesystem.
      - ddrescueview
      - deluge-gtk
      - easytag
      - evince
      - exfalso
      - filelight
      - firefox # shell alias
      - geeqie
      - gimp
      - guvcview
      - handbrake
      - jekyll
      - k3b
      - kcachegrind
      - kcachegrind-converters
      - kcolorchooser
      - kdiff3
      - keepassxc
      - kruler
      - krename
      - libnotify-bin
      - libpurple-bin
      - libreoffice
      - libreoffice-nlpsolver
      - libreoffice-wiki-publisher
      - libreoffice-writer2latex
      - libreoffice-writer2xhtml
      - lyx
      - okular
      - pidgin # NOTE: flatpak doesn't have needed plugins
      - pidgin-bot-sentry
      - pidgin-otr
      - pidgin-plugin-pack
      - retext
      - sigil
      - tellico
      - thunderbird
      - vbindiff
      - virtualbox
      - virtualbox-guest-additions-iso
      - workrave
      - wxhexeditor
      - xchm
      - xkeycaps
      - xpad
      - xsane
      # --== QuickTile ==--
      - gir1.2-glib-2.0
      - gir1.2-gtk-3.0
      - gir1.2-wnck-3.0
      - python3-gi
      - python3-xlib
      # --== Vim with ALE ==--
      - ansible-lint
      - cppcheck
      - eslint
      - flawfinder
      - jsonlint
      - php-codesniffer
      - pydocstyle
      - pylint
      - python3-autopep8
      - python3-bandit
      - python3-flake8
      - python3-isort
      - shellcheck
      - sqlformat
      - uglifyjs
      - valgrind
      - vim-doc
      - vim-gtk # shell alias
      - vulture
      - yamllint
      # --== Infrastructural or stuff I use in scripts/terminal (not suitable for flatpak) ==--
      - advancecomp # shell alias
      - aosd-cat # shell alias
      - arduino-mk
      - bottlerocket # xbindkeys, fan_remote
      - calibre # Not flatpak because I always script it
      - checkinstall
      - cifs-utils
      - clang # for cargo-afl
      - colordiff # shell alias
      - colortest
      - dhex
      - dosbox # Needs scriptable with arbitrary paths for dev so no flatpak
      - encfs
      - expect
      - fbi # ~/bin/gqfbi
      - featherpad
      - festival
      - firejail
      - firejail-profiles
      - fortune-mod
      - fuseiso
      - gaffitter
      - gdb
      - gddrescue
      - graphviz
      - gtk3-nocsd
      - hddtemp
      - htop # shell alias
      - hub # shell alias
      - imagemagick
      - incron
      - iotop
      - irssi
      - jpegoptim
      - latencytop
      - less # pager, manpager, shell alias
      - lgogdownloader # shell alias
      - links
      - links2
      - linux-tools-common
      - linux-tools-generic
      - llvm # for cargo-afl
      - lm-sensors
      - lynx
      - mc # shell alias
      - mencoder
      - mplayer # MUSIC_PLAYER when DISPLAY is unset
      - mercurial
      - molly-guard
      - mp3check # shell alias
      - mpv
      - mutt
      - ncdu
      - node-typescript
      - normalize-audio
      - numlockx
      - openssh-server
      - optipng # shell alias
      - p7zip-full
      - p7zip-rar
      - pandoc
      - pandoc-citeproc
      - pinfo # shell alias
      - pipenv  
      - plasma-discover-backend-flatpak
      - pngcrush # shell alias
      - postgresql
      - pv
      - pydf # shell alias
      - rdiff-backup
      - safecopy
      - screen
      - scrot
      - smem
      - sox
      - sqlite3
      - sshfs
      - taskwarrior # TODO: Remove the need for this
      - tig
      - timelimit
      - timidity
      - tox
      - ufw
      - units # shell alias
      - unrar
      - uptimed
      - virtualenvwrapper
      - wdiff # shell alias
      - wmctrl
      - xautomation
      - xbindkeys
      - xclip
      - xdotool
      - xpra
      - xserver-xephyr
      - xvfb
      - youtube-dl
      - zram-config
      - zsh
      - zsh-doc
      # --== Infrastructural Packages (not suitable for flatpak) ==--
      - apache2
      - ark
      - conky-all
      - elementary-icon-theme
      - gmrun
      - gpm
      - konq-plugins
      - konqueror # shell alias
      - pavucontrol
      - pcmanfm # default file manager and shell alias
      - pypy
      - python-dbus # active_corners, lap, lgogd_uri, timeclock
      - python-dev
      - python-lxml # addventure_tools, fanfic2ebook, ffcms, ficfan
      - python-nose
      - python-psutil # rdbackup_wrapper
      - python-setuptools
      - python-tz # ffcms
      - python-yaml # addventure_tools, ffcms, ficfan, todo_list
      - python3
      - python3-coverage
      - python3-dbus
      - python3-doc
      - python3-examples
      - python3-lxml
      - python3-nose
      - python3-pil
      - python3-pip
      - python3-setuptools
      - python3-sphinx
      - python3-tidylib # Required to pull in .so dependencies for virtualenvs
      - python3-usb # escpos-cli?
      - python3-yaml # dos_installer
      - python3.8
      - ruby
      - rxvt-unicode
      - ssh-askpass-gnome
      - texlive-xetex
      - ttf-mscorefonts-installer
      - xscreensaver
      - xssproxy
      - yakuake
    apt_remove:
      - ace-of-penguins
      - appmenu-*
      - elisa
      - gpicview
      - gnome-exe-thumbnailer
      - gnumeric
      - gnumeric-common
      - gwenview
      - indicator-applet-appmenu
      - indicator-appmenu
      - kate
      - ktorrent
      - liboverlay-scrollbar
      - light-locker
      - mtpaint
      - modemmanager
      - skanlite
      - sylpheed
      - transmission*
      - unity-gtk2-module
      - unity-gtk3-module
      - vlc
    npm_global_cmds: # TODO: Rework to use npx and then write npj and use that
      # Dependencies for ALE save/format-on-check
      prettier: /usr/bin/prettier
      stylelint-config-recommended: /usr/bin/stylelint
      stylelint: /usr/bin/stylelint
    py3_requirements: # TODO: Use pipx
      - restview
      # Dependencies for ALE save/format-on-check
      - rstcheck
      - vim-vint
    ruby_gems:
      - travis-lint
      - mdl
    samba_family_users:
      - andre
      - beverly
      - nick
      - "{{ my_username }}"

  tasks:
    # ============================== Safety Checks ============================
    - name: Abort if we are running as root
      fail:
        msg: "This playbook must be run as root"
      when: ansible_user_uid != 0

    # =================== Remove Unwanted Preloaded Applications ==============
    # (before potentially wasting bandwidth on them with dist-upgrade)
    - name: Purge undesired Lubuntu/Kubuntu/Ubuntu package preloads
      apt:
        state: absent
        purge: true
        autoremove: true
        name: "{{ apt_remove }}"

    # Remove snaps and block Canonical from slipping them back in
    # TODO: Finish implementing this
    - include: tasks/no_snaps.yml

    # ============================= Configure APT =============================
    - name: "Ensure universe and multiverse are enabled"
      apt_repository:
        repo: >-
          {{ item[0] }}
          http://ca.archive.ubuntu.com/ubuntu/
          {{ansible_distribution_release}}{{ item[1] }}
          {{ item[2] }}
        update_cache: false # I'll do it just once later
      when: ansible_distribution == 'Ubuntu'
      with_nested:
        - ["deb", "deb-src"]
        - ["", "-updates"]
        - ["universe", "multiverse"]

    - name: "Ensure universe and multiverse security updates are enabled"
      apt_repository:
        repo: >-
          {{ item[0] }}
          http://security.ubuntu.com/ubuntu
          {{ansible_distribution_release}}-security
          {{ item[1] }}
        update_cache: false # I'll do it just once later
      when: ansible_distribution == 'Ubuntu'
      with_nested:
        - ["deb", "deb-src"]
        - ["universe", "multiverse"]

    - name: Check for i386 support
      command: dpkg --print-foreign-architectures
      check_mode: false
      changed_when: false
      register: dpkgforeign

    - name: Enable multiarch (i386)
      command: dpkg --add-architecture i386
      changed_when: "'i386' not in dpkgforeign.stdout"

    - name: Add PPAs
      apt_repository:
        repo: "{{ item }}"
        update_cache: false # I'll do it just once later
      with_items:
        - "ppa:deadsnakes/ppa" # Various Python version for tox

    - include: tasks/gcdemu_repo.yml

    # =========================== Update & Upgrade ============================
    - name: Update the package repository cache
      apt:
        update_cache: true
        cache_valid_time: 86400 # 24 hours
    - name: Update all packages to the latest version
      apt:
        upgrade: dist

    # ====================== Install Preferred Packages =======================

    - name: "Accept mscorefonts license"
      debconf:
        name: ttf-mscorefonts-installer
        question: msttcorefonts/accepted-mscorefonts-eula
        value: "true"
        vtype: select

    - name: Install packages available through APT
      apt:
        state: present
        name: "{{ apt_install }}"

    # TODO: Install youtube-dl from the upstream source, with
    #       signature verification. (The PPA-provided versions have fatally
    #       flawed support for updating in one way or another.)

    # TODO: Decide which of these should get their own taskfiles
    - name: Install packages from 3rd-party repos
      apt:
        state: present
        name:
          # TODO: Move these to a tasks/deadsnakes.yml
          - python3.6
          - python3.7
          - python3.8
          - python3.9
          - python3.10

      # REMINDER: Use of the `pip` module must come after `apt` installing pip.
    # TODO: Use pipx
    #- name: Install desired Python 3 packages
    #  pip:
    #    executable: pip3
    #    name: "{{ py3_requirements | join(' ') }}"
    - name: Install desired ruby gems
      gem:
        name: "{{ item }}"
        user_install: false
      with_items: "{{ ruby_gems }}"

    # TODO: Use npx
    #- name: Install desired global npm packages
    #  command: npm install -g -- {{ item.key | quote }} # 'npm' is too slow
    #  args:
    #    creates: "{{ item.value }}" # ...and 'command' would be too
    #  with_dict: "{{ npm_global_cmds }}"

    - include: tasks/earlyoom.yml
    - include: tasks/smartd.yml
    - include: tasks/stunnel.yml
    - include: tasks/no_floppy.yml # Keep 'Floppy Drive' out of 'Places' menu
    - include: tasks/hddtemp.yml # Unprivileged querying of HDD temper.
    - include: tasks/planetfilter.yml # RSS/Atom feed filtering
    - include: tasks/gcdemu.yml # Non-ISO CD/DVD image mounting
    - include: tasks/ufw.yml # Basic firewall setup with exceptions
    - include: tasks/hosts_file.yml # Basic system-wide ad-blocking

    # ====================== Apply General Config Fixes =======================

    - include: tasks/verbose_boot.yml # Boot splashes hinder diagnostics
    - include: tasks/sysctl_networking.yml # Improve security and bufferbloat

    - name: "Disable ads in Ubuntu login MOTD"
      copy:
        src: "etc/default/motd-news"
        dest: "/etc/default/motd-news"
        owner: root
        group: root
        mode: 0644

    - name: "Apply udev policy fixes for various pieces of hardware"
      copy:
        src: "etc/udev/rules.d/"
        dest: "/etc/udev/rules.d/"
        owner: root
        group: root
        mode: 0644

    - name: "Enable magic SysRq key"
      copy:
        src: "etc/sysctl.d/10-magic-sysrq.conf"
        dest: "/etc/sysctl.d/10-magic-sysrq.conf"
        owner: root
        group: root
        mode: 0644

    - name: "Make custom update_check.sh passwordless"
      copy:
        src: "etc/sudoers.d/update_checker"
        dest: "/etc/sudoers.d/update_checker"
        owner: root
        group: root
        mode: 0440

    - name: "Set up lm_sensors" # noqa 306
      shell: "yes | sensors-detect"
      args:
        creates: /etc/sensors3.conf

    - name: "Linking virtualbox to virtualbox-ose for old VM snapshot CD paths"
      file:
        src: virtualbox
        dest: /usr/share/virtualbox-ose
        state: link

    - name: "Create 'family' group"
      group:
        name: family
        state: present

    - name: "Change login shell to zsh for {{ my_username }} and add groups"
      user:
        name: "{{ my_username }}"
        append: true
        groups: tty,dialout,video,lpadmin,vboxusers,family
        shell: /bin/zsh

    - name: "Add {{ my_username }} to incron allowed users"
      lineinfile:
        path: /etc/incron.allow
        line: "{{ my_username }}"
        create: true

    # ================== Install monolith-specific Packages ===================

    - include: tasks/wine.yml # Wine and PlayOnLinux, with 16-bit support
      when: ansible_hostname == my_hostname

    # ---- Network Services

    - include: tasks/samba.yml # media server and file drop box
      when: ansible_hostname == my_hostname

    - include: tasks/nostalgia_exchange.yml # Munin master and monitoring node
      when: ansible_hostname == my_hostname

    - include: tasks/router_syslog.yml # Enable reception of router syslog
      when: ansible_hostname == my_hostname

    # ---- Hardware Drivers

    - include: tasks/lcdproc.yml # front-panel diagnostic LCD
      when: ansible_hostname == my_hostname

    - include: tasks/spacenavd.yml # 3D Connexion Space Navigator driver
      when: ansible_hostname == my_hostname

    - include: tasks/truerng.yml # TrueRNG hardware RNG driver
      when: ansible_hostname == my_hostname

    # TODO: Is this still necessary for *buntu 20.04 LTS?
    # - include: tasks/pa_tsched_fix.yml
    #   when: ansible_hostname == my_hostname

    - include: tasks/nvidia_config.yml # Driver and config for my TwinView
      when: ansible_hostname == my_hostname
# ==================== Apply monolith-specific Config =====================
