---
# NOTE: Requires 'libssl-dev' to be installed

- hosts: localhost
  connection: local

  vars:
    rust_commands:
      - afl
      - cross
      - cargo-deadlinks
      - cargo-spellcheck
      - cargo-watch
      - flamegraph
      - typos-cli
      - zbus_xmlgen
      # Bloat analysis
      - cargo-bloat
      - cargo-llvm-lines
      # Build automation
      - cargo-make
      - just
      # Dependency inspection
      - cargo-audit
      - cargo-outdated
      - cargo-feature-set
      - cargo-geiger
      # Dependency license analysis
      - cargo-about
      - cargo-deny
      - cargo-license
      - cargo-lichking
      # Dependency management
      - cargo-cache
      - cargo-prune
      - cargo-sweep
      - cargo-edit
      - cargo-update
      # Generated code inspection
      - cargo-asm
      - cargo-expand
      # Utilities for the system at large
      - bat
      - fd-find
      - hyperfine
      - jsonfmt
      - procs
      - rust-script
      - skim
      - tokei
      - xd
    rust_commands_nightly:
      - cargo-fuzz
      - miniserve
    rust_targets:
      # Default non-cross-compilation arch
      - "{{ ansible_userspace_architecture }}-unknown-linux-gnu"
      # musl-libc cross-compilation for static Linux builds
      - i686-unknown-linux-musl
      - x86_64-unknown-linux-musl
      # OpenPandora cross-compilation
      - arm-unknown-linux-gnueabi
    rust_toolchains:
      - "stable-{{ ansible_userspace_architecture }}-unknown-linux-gnu"
      - "nightly-{{ ansible_userspace_architecture }}-unknown-linux-gnu"

  tasks:
    # ============================= Safety Checks =============================
    - name: Verify that ansible_user_id isn't set to root
      fail:
        msg: "This playbook must be run as {{ my_username }}"
      when: ansible_user_uid == my_username

    # ========================= Set Up User Profile ==========================

    - name: Remove snap-related folders in user profile
      file:
        state: absent
        path: ~/snap

    - name: Check whether installed crontab differs
      command: ./helper_scripts/diff_crontab.py
      register: diff_crontab
      changed_when: "diff_crontab.stdout != ''"

    - name: Install crontab for {{ my_username }}
      command: crontab supplemental/crontab_backup
      when: diff_crontab.changed
      changed_when: true

    # NOTE: See also `export WINEDLLOVERRIDES="winemenubuilder.exe=d"`
    #       in ~/.common_sh_init/env
    - name: Set PlayOnLinux to use private user dirs and not make desktop icons
      lineinfile:
        path: ~/.PlayOnLinux/configurations/post_prefixcreate
        line: "{{ item }}"
        create: true
      with_items:
        - "POL_Call POL_Install_PrivateUserDirs"
        - 'POL_Config_Write NO_DESKTOP_ICON "TRUE"'

    # ===================== Install Preferred Packages ========================
    # TODO: Re-identify all the packages installed on my system that I want to
    #       reinstall.

    - name: Check if rustup is installed
      stat:
        path: ~/.cargo/bin/rustup
      register: rustup_stat

    - name: Download rustup.sh
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/rustup.sh
        mode: 0755
        owner: "{{ my_username }}"
        checksum: sha256:fa50ccf79c30ce9446cc45917e8ea10655674c2a9509221cb12bd865c60ab709
      when: not rustup_stat.stat.exists

    - name: Install rustup using rustup.sh
      command: /tmp/rustup.sh -y
      args:
        creates: ~/.cargo/bin/rustup
      when: not rustup_stat.stat.exists

    - name: Ensure existing rustup-managed components are up to date
      command: $HOME/.cargo/bin/rustup update
      register: rustup_update
      changed_when: "'updated' in rustup_update.stdout"

    # Use "creates" to save time since `rustup update` will handle updates
    - name: Install rust toolchains
      command: ~/.cargo/bin/rustup toolchain install "{{ item }}"
      args:
        creates: "~/.rustup/toolchains/{{ item }}"
      with_items: "{{ rust_toolchains }}"

    # Use "creates" to save time since `rustup update` will handle updates
    - name: Install rust targets
      command: ~/.cargo/bin/rustup target add --toolchain "{{ item[0] }}" "{{ item[1] }}"
      args:
        creates: "~/.rustup/toolchains/{{ item[0] }}/lib/rustlib/{{ item[1] }}"
      with_nested:
        - "{{ rust_toolchains }}"
        - "{{ rust_targets }}"

    # NOTE: Calls to `cargo install` don't use "creates" because cargo should
    #       handle "no rebuild needed" detection.
    - name: Install sccache with support for distributed compilation
      command: ~/.cargo/bin/cargo install --features="dist-client dist-server" sccache
      register: sccacheinstall
      changed_when: "'is already installed' not in sccacheinstall.stderr"
      environment:
        RUSTFLAGS: "-C target-cpu=native"

    - name: Install a cargo config that uses sccache by default
      template:
        src: cargo_config
        dest: ~/.cargo/config

    - name: Install developer commands
      command: ~/.cargo/bin/cargo install {{ item }}
      register: cargoinstall
      changed_when: "'is already installed' not in cargoinstall.stderr"
      with_items: "{{ rust_commands }}"
      environment:
        RUSTFLAGS: "-C target-cpu=native"

    - name: Install nightly-requiring developer commands
      command: ~/.cargo/bin/cargo +nightly install {{ item }}
      register: cargoinstallnightly
      changed_when: "'is already installed' not in cargoinstallnightly.stderr"
      with_items: "{{ rust_commands_nightly }}"
      environment:
        RUSTFLAGS: "-C target-cpu=native"

    - name: Install ripgrep
      command: ~/.cargo/bin/cargo +nightly install ripgrep --features 'simd-accel'
      register: cargoripgrep
      changed_when: "'is already installed' not in cargoripgrep.stderr"
      environment:
        RUSTFLAGS: "-C target-cpu=native"

    # TODO: Is there a way to make this conditional on a repo update?
    - name: Install rustig
      command: ~/.cargo/bin/cargo install --git https://github.com/MichaelMauderer/rustig rustig
      args:
        creates: "~/.cargo/bin/rustig"

    - name: Install rust-analyzer
      get_url:
        # yamllint disable-line rule:line-length
        url: "https://github.com/rust-analyzer/rust-analyzer/releases/latest/download/rust-analyzer-linux"
        dest: "~/.cargo/bin/rust-analyzer"
        mode: 0755
    # yamllint disable-line rule:line-length rule:comments-indentation
    # TODO: https://pyra-handheld.com/boards/threads/how-to-cross-compile-rust-programs.78650/#post-1398907
