---
- name: Install firejail
  apt:
    state: present
    name:
      - firejail
      - firejail-profiles
  tags:
    - firejail

- name: Install custom firejail policy tweaks
  copy:
    src: "etc/firejail/"
    dest: "/etc/firejail/"
    owner: root
    group: root
    mode: 0644
  tags:
    - firejail

- name: Disable Firejail sandboxing of Dolphin
  # ... so invoking Flatpak apps by double-clicking works
  lineinfile:
    path: /usr/lib/x86_64-linux-gnu/firejail/firecfg.config
    regexp: "^\\s*dolphin\\s*$"
    line: "# dolphin"
  tags:
    - firejail

- name: Install firejail wrapper symlinks
  command: firecfg
  changed_when: false
  tags:
    - firejail
