---
# Set up an ad-blocking hosts file with some custom local entries

- name: Copy local /etc/hosts components into place
  copy:
    src: etc/hosts.local
    dest: /etc/hosts.local
    owner: root
    group: root
    mode: 0644
    backup: true
  register: hosts_l

# My home-grown HOSTS file updater which sanitizes input
- name: Download HOSTS file updater
  get_url:
    url: "http://ssokolow.com/scripts/upd_hosts.py"
    dest: "/etc/cron.monthly/upd_hosts.py"
    owner: root
    group: root
    mode: 0755
    timeout: 5
    checksum: "sha256:da272587722e7e338aca9753423853df1d8c69e78fce37f6177f2be30f43ffdf"
  register: hosts_u

- name: Download updated MVPS HOSTS file and merge in local amendments
  command: /etc/cron.monthly/upd_hosts.py
  when: hosts_l.changed or hosts_u.changed
