---
# TODO: Fix immutable-setting so it doesn't always report unchanged
# See https://github.com/ansible/ansible/issues/48886
- name: Temporarily unset immutable filesystem attribute on xorg.conf
  command: chattr -i /etc/X11/xorg.conf
  changed_when: false
  failed_when: false

- name: Set preferred X.org configuration
  copy:
    src: etc/X11/xorg.conf
    dest: /etc/X11/xorg.conf
    owner: root
    group: root
    mode: 0644

- name: Reset immutable filesystem attribute on xorg.conf
  command: chattr +i /etc/X11/xorg.conf
  changed_when: false

- name: Copy deferred nVidia driver update helper into place
  copy:
    src: usr/local/sbin/update_nvidia
    dest: /usr/local/sbin/update_nvidia
    owner: root
    group: root
    mode: 0755

- name: Install systemd service for deferred nVidia driver update helper
  copy:
    src: etc/systemd/system/update_nvidia.service
    dest: /etc/systemd/system/update_nvidia.service
    owner: root
    group: root
    mode: 0644

- name: Enable systemd service for deferred nVidia driver update helper
  ansible.builtin.systemd:
    name: update_nvidia
    enabled: yes
    masked: no

- name: Run update_nvidia once to set up initial package pins
  command: /usr/local/sbin/update_nvidia --mark-only
  changed_when: false
