#!/usr/bin/zsh
# This hook is run after every virtualenv is activated.
# Source: http://www.doughellmann.com/docs/virtualenvwrapper/tips.html

# Automatically CD to the project directory if set
export PRE_VENV_ACTIVATE_DIR=`pwd`
cdproject

# Ensure zsh updates its command path cache
rehash
